name: PR Verify

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: PR Verify
    uses: tracy04GH/reusable-workflows/.github/workflows/reusable-build.yml@main
    with:
      dotnet_version: 9.0.x